keys:
  - cipher: chacha20-ietf-poly1305
    id: '0'
    port: 64563
    secret: oOBo3ajVTwZp7NP97ihOAh
  - cipher: chacha20-ietf-poly1305
    id: '1'
    port: 64563
    secret: U3gPtImsXh3hHYWpy6zEgh
  - cipher: chacha20-ietf-poly1305
    id: '2'
    port: 64563
    secret: Q1EzG7a9ZyoKEh0eq31BIx
  - cipher: chacha20-ietf-poly1305
    id: '5'
    port: 64563
    secret: l12S38Z4f6R196qBME6EP1
  - cipher: chacha20-ietf-poly1305
    id: '6'
    port: 64563
    secret: cLEMRZn2dGX350cEPiaVAg
  - cipher: chacha20-ietf-poly1305
    id: '9'
    port: 64563
    secret: oUACZIyslVyKyKmLS9S3JI
  - cipher: chacha20-ietf-poly1305
    id: '10'
    port: 64563
    secret: m9Nl58qBCOqQWoML1sEp8l
  - cipher: chacha20-ietf-poly1305
    id: '11'
    port: 64563
    secret: dbcLs4Lh8vq7BXaUBb2mnv
  - cipher: chacha20-ietf-poly1305
    id: '12'
    port: 64563
    secret: pl4eBAM03uD5DxnxmVtrBu
  - cipher: chacha20-ietf-poly1305
    id: '13'
    port: 64563
    secret: qZAXhp73VzMEvN1LfrnPZs
  - cipher: chacha20-ietf-poly1305
    id: '14'
    port: 64563
    secret: QqgSiSzj9SNtXZCJkjdA1l
  - cipher: chacha20-ietf-poly1305
    id: '15'
    port: 64563
    secret: 4ihxBIGfsWjMhL8geoGR7W
  - cipher: chacha20-ietf-poly1305
    id: '16'
    port: 64563
    secret: LT2cpyzvvN1siqPwoyYOFc
  - cipher: chacha20-ietf-poly1305
    id: '17'
    port: 64563
    secret: Bw8IsOZxSaz4mZOGWa76AT
  - cipher: chacha20-ietf-poly1305
    id: '18'
    port: 64563
    secret: EKGTbRMjtAuQYIJZQ7S678
  - cipher: chacha20-ietf-poly1305
    id: '19'
    port: 64563
    secret: 2vLwhsLQCGQwk4WKq4ivkw
  - cipher: chacha20-ietf-poly1305
    id: '20'
    port: 64563
    secret: EVY91Q9g27CbI0TlY1oJyl
  - cipher: chacha20-ietf-poly1305
    id: '21'
    port: 64563
    secret: Jy0vEZyGsBwG0EdJlUZqjP
  - cipher: chacha20-ietf-poly1305
    id: '22'
    port: 64563
    secret: LarQ25qeSVvrcF7yHMNDkA
  - cipher: chacha20-ietf-poly1305
    id: '23'
    port: 64563
    secret: xGj7y6VtFWm37aH3btgNAb
  - cipher: chacha20-ietf-poly1305
    id: '24'
    port: 64563
    secret: Bar90TvDmwmEihQj2KlHBW
  - cipher: chacha20-ietf-poly1305
    id: '25'
    port: 64563
    secret: d4phmMj1IZHyufs48wPc7g
  - cipher: chacha20-ietf-poly1305
    id: '27'
    port: 64563
    secret: yTqXJWMiwZgSIfH43f0P1K
  - cipher: chacha20-ietf-poly1305
    id: '28'
    port: 64563
    secret: 50JMoXTjRNtVuRFU5EIkF2
  - cipher: chacha20-ietf-poly1305
    id: '29'
    port: 64563
    secret: g7PEzaRNXIYHMktXRc2p1N
  - cipher: chacha20-ietf-poly1305
    id: '30'
    port: 64563
    secret: zSJpdtZKvtmd5WrtO5KaKy
  - cipher: chacha20-ietf-poly1305
    id: '31'
    port: 64563
    secret: FqrFlJVk0w4NpCkdMrVwF2
  - cipher: chacha20-ietf-poly1305
    id: '32'
    port: 64563
    secret: EJYly1vMaUxAqh4JC0cdH8
  - cipher: chacha20-ietf-poly1305
    id: '35'
    port: 64563
    secret: i1K1X8LorcN4s2ZQPWpqoU
  - cipher: chacha20-ietf-poly1305
    id: '36'
    port: 64563
    secret: FH83hkw5tkmixlbbiI9NGl
  - cipher: chacha20-ietf-poly1305
    id: '37'
    port: 64563
    secret: vVGerjxdhlvcQ0LQt9mTCH
  - cipher: chacha20-ietf-poly1305
    id: '38'
    port: 64563
    secret: UX62XaXlTquVzu0pmA9sr2
  - cipher: chacha20-ietf-poly1305
    id: '39'
    port: 64563
    secret: 0WfvIrA5eezJqUXi4QixDi
  - cipher: chacha20-ietf-poly1305
    id: '40'
    port: 64563
    secret: VVvpCLDEAxbIBUoKLifB7O
  - cipher: chacha20-ietf-poly1305
    id: '41'
    port: 64563
    secret: bN1rW8nh6u1sgcPDBWyOZ9
  - cipher: chacha20-ietf-poly1305
    id: '43'
    port: 64563
    secret: RuLFvM4p4rk7e2EQVWYedj
  - cipher: chacha20-ietf-poly1305
    id: '44'
    port: 64563
    secret: kRNMmtn3K4g8TUqx8sOKIW
  - cipher: chacha20-ietf-poly1305
    id: '45'
    port: 64563
    secret: 5lWl2BDfOtV2Owlw6Ti95H
  - cipher: chacha20-ietf-poly1305
    id: '46'
    port: 64563
    secret: hOv8aMIZgcV7GDRc9fBcur
  - cipher: chacha20-ietf-poly1305
    id: '47'
    port: 64563
    secret: fKWUKJQVnC1ShxEx0O5ngb
  - cipher: chacha20-ietf-poly1305
    id: '48'
    port: 64563
    secret: Tsw4WOttQT7RPR6d7kToQD
  - cipher: chacha20-ietf-poly1305
    id: '50'
    port: 64563
    secret: zOZq82pcOgZOc3VSkcFhVM
  - cipher: chacha20-ietf-poly1305
    id: '51'
    port: 61595
    secret: gE5lCJQJhNOFf5tt3478n4
  - cipher: chacha20-ietf-poly1305
    id: '52'
    port: 51600
    secret: QRRQIYo0XyuB3HPcUzy61a
